spring:
  datasource:
    url: jdbc:postgresql://y-postgres-postgresql.development.svc.cluster.local:5432/auth
    username: postgres
    password: bHa8Hn9OBm
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    enabled: true

server:
  port: 8092



management:
  endpoint:
    health:
      enabled: true
